linux:
  enabled: true
  image:
    repository: docker.io/bdlb77/secrets-store-csi
    tag: v0.0.9
    pullPolicy: Always
  reconciler:
    image:
      repository: docker.io/bdlb77/secrets-store-reconciler
      tag: v0.0.1
      pullPolicy: Always

windows:
  enabled: false
  image:
    repository: mcr.microsoft.com/k8s/csi/secrets-store/driver
    tag: v0.0.9
    pullPolicy: IfNotPresent

logLevel:
  debug: true

livenessProbe:
  port: 9808

## Install Default RBAC roles and bindings
rbac:
  install: true

## Minimum Provider Versions (optional)
## A comma delimited list of key-value pairs of minimum provider versions
## e.g. provider1=0.0.2,provider2=0.0.3
minimumProviderVersions:
