apiVersion: secrets-store.csi.x-k8s.io.secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClassPodStatus
metadata:
  name: secretproviderclasspodstatus-sample
spec:
  # Add fields here
  foo: bar
